site_name: 竺院辅学计划站点
site_url: https://ckc-agc.pages.zjusct.io/study-assist/
repo_url: https://github.com/ckc-agc/study-assist
repo_name: 竺院辅学计划站点
edit_uri: tree/master/docs
site_description: 竺院辅学计划站点
site_author: 竺可桢学院学业指导中心

theme:
  name: material
  logo: graph/ckc.png
  favicon: graph/ckc.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  features:
    - search.highlight
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.action.edit
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  # Python Markdown
  - toc:
      permalink: true
      toc_depth: 2
  - abbr
  - def_list
  - attr_list
  - footnotes
  - md_in_html
  - admonition
  - sane_lists
  # Python Markdown Extensions
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - neoteroi.cards # install using `pip install neoteroi-mkdocs`
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/neoteroi-mkdocs.css
  - stylesheets/custom.css

plugins:
  - search
  - glightbox # install using `pip install mkdocs-glightbox`
  - heti:
      extra_skipped_class:
        - arithmatex
      disable_serve: false


nav:
  - 首页: 
    - index.md
    - 测试: test.md
  - 📚微积分:
    - calculus/index.md
  - 📚数学分析:
    - analysis/index.md
    - 历年卷整理: analysis/exam.md
    - 2023 年辅学资料: analysis/2023/index.md
  - 📚线性代数:
    - algebra/index.md
  - 🏫线性代数：未竟之美:
    - lalu/index.md
  - 📚程设:
    - programming/index.md
    - FAQ: programming/faq.md
    - 历年卷:
      - programming/exam/index.md
#      - C 小历年卷常见问题总结: programming/exam/fp.md
#      - C 大历年卷常见问题总结: programming/exam/lcp.md
#    - 2023 年辅学资料: programming/2023/index.md
  - 🏫实用技能拾遗:
    - PracticalSkillsTutorial/index.md
  - 🏫系统知识拾遗:
    - programming_lecture/index.md
    - 1. 程序编译过程与调试技术:
      - 准备开发与调试环境: programming_lecture/lecture1/pre_class.md
      - 课程讲义: programming_lecture/lecture1/lecture1.md
  - 📚普通化学:
    - chemistry/index.md
  - 📚普通物理学:
    - physics/index.md