site_name: 浙江大学竺可桢学院辅学计划站点
site_url: https://ckc-agc.pages.zjusct.io/study-assist/
repo_url: https://github.com/ckc-agc/study-assist
repo_name: 浙江大学竺可桢学院辅学计划站点
edit_uri: tree/master/docs
site_description: 浙江大学竺可桢学院辅学计划站点
site_author: 竺可桢学院学业指导中心

theme:
  name: material
  logo: graph/ckc.png
  favicon: graph/ckc.png
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  features:
    - search.highlight
#    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - header.autohide
    - content.code.copy
    - content.code.annotate
    - content.action.edit
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  # Python Markdown
  - toc:
      permalink: true
      toc_depth: 3
  - abbr
  - def_list
  - attr_list
  - footnotes
  - md_in_html
  - admonition
  - sane_lists
  # Python Markdown Extensions
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - neoteroi.cards # install using `pip install neoteroi-mkdocs`


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://jsd.onmicrosoft.cn/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/neoteroi-mkdocs.css
  - stylesheets/custom.css

plugins:
  - search
  - glightbox # install using `pip install mkdocs-glightbox`
  - heti:
      extra_skipped_class:
        - arithmatex
      disable_serve: false
  - git-revision-date-localized
#  - git-authors
#  - git-committers


nav:
  - 首页: 
    - index.md
    - 测试: test.md
  - 📚微积分:
    - calculus/index.md
  - 📚数学分析:
    - analysis/index.md
    - 2023-2024学年:
      - analysis/2024/analysis_lecture1_sequence_limits.md
  - 📚线性代数:
    - algebra/index.md
  - 🏫线性代数：未竟之美:
    - lalu/index.md
  - 📚程设:
    - programming/index.md
    - 每日一题: programming/2024_daily_problem.md
    - 常见问题: programming/faq.md
#      - C 小历年卷常见问题总结: programming/exam/fp.md
#      - C 大历年卷常见问题总结: programming/exam/lcp.md
#    - 2023 年辅学资料: programming/2023/index.md
  - 🏫实用技能拾遗: https://slides.tonycrane.cc/PracticalSkillsTutorial/2023-fall-ckc/#/
  - 🏫系统知识拾遗:
    - programming_lecture/index.md
    - 1. 程序编译过程与调试技术:
      - programming_lecture/lecture1/pre_class.md
      - programming_lecture/lecture1/lecture1.md
    - 2. 类型系统与内存模型:
      - programming_lecture/lecture2/lecture2.md
    - 3. I/O 与文件:
      - programming_lecture/lecture3/lecture3.md
    - 4. C 标准库:
      - programming_lecture/lecture4/lecture4.md
    - 5. 数据结构与算法:
      - programming_lecture/lecture5/lecture5.md
  - 📚普通化学:
    - chemistry/index.md
  - 📚普通物理学:
    - physics/index.md
